# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/s3-bucket.yaml"
stack_name: rna-seq-reprocessing-scicomp-toil-cluster-v001-out
stack_tags: {{stack_group_config.stack_tags}}
dependencies:
  - prod/rna-seq-reprocessing-instance-role-v001.yaml
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "IBC"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "amp-ad"
  # The resource owner
  OwnerEmail: "dpe@sagebase.org"

  # The following parameters are only examples they are not required.
  # You may omit them if you do not need to override the defaults.

  # (Optional) true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: 'true'
  # (Optional) Synapse username (default: ""), required if AllowWriteBucket=true
  SynapseUserName: 'wpoehlm'
  # (Optional) Allow accounts, groups, and users to access bucket (default is no access).
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required ARN for a synapse bucket
    - 'arn:aws:iam::563295687221:user/tess.thyer@sagebase.org'
    - 'arn:aws:iam::563295687221:user/william.poehlman@sagebase.org'
    - 'arn:aws:iam::055273631518:role/rna-seq-reprocessing-instance-role-v00-ClusterRole-1DKFCADNB2RWQ'

  # Restrict downloading files from this bucket to only AWS resources (e.g. EC2 , Lambda)
  # within the same region as this bucket.  This will not allow even the owner of the bucket
  # to download objects in this bucket when not using an AWS resource in the same region!
  SameRegionResourceAccessToBucket: "false"
  BucketName: "rna-seq-reprocessing-scicomp-toil-cluster-v001-out"
