# Provision an EC2 instance
template:
  path: toil-instance.yaml
stack_name: rna-seq-reprocessing-scicomp-jumpbox-v001
stack_tags: {{stack_group_config.stack_tags}}
dependencies:
  - prod/toil-infra-essentials.yaml
  - prod/rna-seq-reprocessing-instance-role-v001.yaml
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "SysBio"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "amp-ad"
  # A sub-project
  SubProject: "amp-ad-workflows"
  # The resource owner
  OwnerEmail: "tess.thyer@sagebase.org"

  VpcName: "{{stack_group_config.default_vpc}}"
  KeyName: "{{stack_group_config.toil_key_pair}}"
  AMIId: "{{stack_group_config.toil_ami}}"
  RoleStackName: "rna-seq-reprocessing-instance-role-v001"

  RsaKey: !ssm /toil-cluster-infra/SshKey
  PublicRsaKey: !ssm /toil-cluster-infra/PublicSshKey
  ClusterName: rna-seq-reprocessing-scicomp-toil-cluster-v001
  ToilAppliance: quay.io/tessthyer/toil:3.21.0a1-e33659ee03212db3378dfed80b43362038fd21f3
  ClusterLeaderNodeType: m5.2xlarge
  ClusterLeaderStorage: "500"

  # Settings have default values but can be overriden. Set the below
  # parameters *only* if you want to override the defaults.

  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/pricing/on-demand/)
  # InstanceType: "t2.medium"
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  # VolumeSize: "50"
  # (Optional) Set true to enable daily backups (default: false)
