template:
  path: toil-infra-essentials.yaml
stack_name: toil-infra-essentials
stack_tags: {{stack_group_config.stack_tags}}
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "IBC"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "amp-ad"
  # A sub-project
  SubProject: "amp-ad-workflows"
  # The resource owner
  OwnerEmail: "dpe@sagebase.org"
