sudo: false
language: python
python: 3.6
cache: pip
fast_finish: true
branches:
  only:
  - develop
  - prod
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install pre-commit sceptre sceptre-ssm-resolver
  - pip install git+git://github.com/Sage-Bionetworks/sceptre-provisioner-hooks.git
stages:
  - name: validate
  - name: deploy
    if: type = push
jobs:
  include:
    - stage: validate
      script:
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: deploy
      script:
        - travis_wait 30 sceptre launch $TRAVIS_BRANCH --yes
