project_code: sage-bionetworks
profile: {{ var.profile | default("default") }}
region: {{ var.region | default("us-east-1") }}
template_bucket_name: bootstrap-awss3cloudformationbucket-z6hnifi9i3p
template_key_prefix: {{ environment_variable.TRAVIS_BRANCH | default("testing") }}
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
default_ubuntu_ami: "ami-0a313d6098716f372"
default_toil_ubuntu_ami: "ami-032e0d8fe5cfa8c7f"
