project_code: sage-bionetworks
profile: {{ var.profile | default("default") }}
region: {{ var.region | default("us-east-1") }}
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
template_key_prefix: {{ environment_variable.TRAVIS_BRANCH | default("testing") }}
toil_key_pair: "toil"
toil_ami: "ami-024a64a6685d05041" #ubuntu 18.04
