# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template_path: remote/s3-bucket.yaml
stack_name: rna-seq-reprocessing-toil-cluster-v001-out
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "SysBio"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "amp-ad"
  # The resource owner
  OwnerEmail: 'tess.thyer@sagebase.org'

  # The following parameters are only examples they are not required.
  # You may omit them if you do not need to override the defaults.

  # (Optional) true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: 'true'
  # (Optional) Synapse username (default: ""), required if AllowWriteBucket=true
  SynapseUserName: 'wpoehlm'
  # (Optional) Allow accounts, groups, and users to access bucket (default is no access).
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required ARN for a synapse bucket
    - 'arn:aws:iam::563295687221:user/tess.thyer@sagebase.org'
    - 'arn:aws:iam::563295687221:user/william.poehlman@sagebase.org'
    - 'arn:aws:iam::563295687221:role/rna-seq-reprocessing-instance-role-v00-ClusterRole-1QAEKIKZY9I2L'

  # Restrict downloading files from this bucket to only AWS resources (e.g. EC2 , Lambda)
  # within the same region as this bucket.  This will not allow even the owner of the bucket
  # to download objects in this bucket when not using an AWS resource in the same region!
  SameRegionResourceAccessToBucket: "true"
  BucketName: "rna-seq-reprocessing-toil-cluster-v001-out"

# For CI system (do not change)
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/s3-bucket.yaml --create-dirs -o templates/remote/s3-bucket.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/s3-bucket.yaml --create-dirs -o templates/remote/s3-bucket.yaml"
