AWSTemplateFormatVersion: 2010-09-09
Resources:
  AWSServiceRoleForEC2Spot:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSServiceRoleForEC2Spot
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - spot.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/aws-service-role/AWSEC2SpotServiceRolePolicy
