AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ClusterName:
    Description: Name of the cluster that will use these resources.
    Type: String
Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Ref ClusterPolicy
        - !Ref TagRootVolumePolicy
  ClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref ClusterRole
  ClusterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Minimal permissions for toil instances.
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:CancelSpotInstanceRequests
              - ec2:CreateSecurityGroup
              - ec2:CreateTags
              - ec2:DeleteSecurityGroup
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeInstanceStatus
              - ec2:DescribeKeyPairs
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSpotInstanceRequests
              - ec2:DescribeSpotPriceHistory
              - ec2:DescribeVolumes
              - ec2:RequestSpotInstances
              - ec2:RunInstances
              - ec2:StartInstances
              - ec2:StopInstances
              - ec2:TerminateInstances
              - iam:PassRole
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:DeleteObject
              - s3:DeleteObjectVersion
              - s3:GetBucketLocation
              - s3:GetBucketVersioning
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetObjectVersionTagging
              - s3:HeadBucket
              - s3:ListAllMyBuckets
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListBucketVersions
              - s3:ListMultipartUploadParts
              - s3:PutBucketTagging
              - s3:PutBucketVersioning
              - s3:PutObject
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
              - s3:ReplicateTags
            Resource: !Sub "arn:aws:s3:::${ClusterName}*"
          - Effect: Allow
            Action:
              - sdb:*
            Resource: !Sub "arn:aws:sdb:${AWS::Region}:${AWS::AccountId}:domain/${ClusterName}*"
  TagRootVolumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow instances to apply tags to root volume. Like TagRootVolumeRole in aws-infra/essentials.
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "ec2:Describe*"
              - "ec2:CreateTags"
            Resource: "*"
Outputs:
  ToilClusterRole:
    Description: Role for toil instances.
    Value: !GetAtt ClusterRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ToilClusterRole'