AWSTemplateFormatVersion: 2010-09-09
Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::563295687221:policy/toil-cluster-instance-policy
  ClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: toil-cluster-instance-role
      Path: "/"
      Roles:
        - toil-cluster-instance-role
  ClusterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Minimal permissions for toil instances.
      ManagedPolicyName: toil-cluster-instance-policy
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:CancelSpotInstanceRequests
              - ec2:CreateSecurityGroup
              - ec2:CreateTags
              - ec2:DeleteSecurityGroup
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeInstanceStatus
              - ec2:DescribeKeyPairs
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSpotInstanceRequests
              - ec2:DescribeSpotPriceHistory
              - ec2:DescribeVolumes
              - ec2:RequestSpotInstances
              - ec2:RunInstances
              - ec2:StartInstances
              - ec2:StopInstances
              - ec2:TerminateInstances
              - iam:PassRole
              - s3:AbortMultipartUpload
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:DeleteObject
              - s3:DeleteObjectVersion
              - s3:GetBucketLocation
              - s3:GetBucketVersioning
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetObjectVersionTagging
              - s3:HeadBucket
              - s3:ListAllMyBuckets
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListBucketVersions
              - s3:ListMultipartUploadParts
              - s3:PutBucketTagging
              - s3:PutBucketVersioning
              - s3:PutObject
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
              - s3:ReplicateTags
              - sdb:*
            Resource: "*"
